-- CREATE TABLE sharpautos (
--          id int NOT NULL AUTO_INCREMENT,
--          creatorId int NOT NULL,
--          title VARCHAR(255) NOT NULL,
--          make VARCHAR(255) NOT NULL,
--          model VARCHAR(255) NOT NULL,
--          year int,
--          color VARCHAR(255) NOT NULL,
--          listingdescription VARCHAR(255),
--          listinglocation VARCHAR(255) NOT NULL,
--          imageurl VARCHAR(255),
--          price DECIMAL(65,2) NOT NULL,
--          PRIMARY KEY (id)
--       );

-- CREATE TABLE sharpproperties (
--          id int NOT NULL AUTO_INCREMENT,
--          creatorId int NOT NULL,
--          title VARCHAR(255) NOT NULL,
--          zoning VARCHAR(255) NOT NULL,
--          squarefootage int NOT NULL,
--          yearbuilt int NOT NULL,
--          color VARCHAR(255) NOT NULL,
--          listingdescription VARCHAR(255),
--          listinglocation VARCHAR(255),
--          imageurl VARCHAR(255),
--          price DECIMAL(65,2) NOT NULL,
--          PRIMARY KEY (id)
--       );

-- CREATE TABLE sharpanimals (
--     id int NOT NULL AUTO_INCREMENT,
--     creatorId int NOT NULL,
--     title VARCHAR(255) NOT NULL,
--     animalname VARCHAR(255) NOT NULL,
--     species VARCHAR(255) NOT NULL,
--     breed VARCHAR(255) NOT NULL,
--     age int,
--     color VARCHAR(255) NOT NULL,
--     listingdescription VARCHAR(255),
--     listinglocation VARCHAR(255) NOT NULL,
--     medicalconcerns VARCHAR(255) NOT NULL,
--     imageurl VARCHAR(255),
--     price DECIMAL(65,2) NOT NULL,
--     PRIMARY KEY (id)
-- );